export const CONST_TRANSITION = {
  AUTH_LOGO: 'AUTH_LOGO',
  AUTH_TITLE: 'AUTH_TITLE',
  AUTH_DESCRIPTION: 'AUTH_DESCRIPTION',

  CURRENT_USER_AVATAR: 'CURRENT_USER_AVATAR',
  CURRENT_USER_NAME: 'CURRENT_USER_NAME',
};
